data_info:
  name: ""  # Choose the dataset used: FAVC (FakeAVCeleb), AV1M (AV-Deepfake1M), AVLips
  root_path: ""  # Data root path 
  avhubert_model: "self_large_vox_433h"  # AVHuBERT checkpoint
  csv_root_path: ""  # Path to the folder containing split csv's
  apply_l2: True  # Apply l2 normalization of input features (always used in our experiments)

hparams_path: ""  # Path to the hparams generated for the model 
ckpt_path: ""  # Path to the model ckpt

output_path: ""  # Path to output folder

seed: 43